[package]
name = "image-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
glfw = { version = "0.59.0", features = ["vulkan"] }

[dev-dependencies]
libloading = "0.8.6"
