[package]
name = "image-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
glam = "0.29.2"
winit = "0.30.8"
libloading = "0.8.6"

[features]
default = ["debug"]
debug = ["glam/glam-assert"]
