[package]
name = "image-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
glm = "0.2.3"
winit = "0.30.8"

[dev-dependencies]
libloading = "0.8.6"
